on:
  schedule:
  - cron: "0 0 7 * *"
  push:
    branches:
      - master

name: update-relatorios

jobs:
  update-data:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instalar R
        uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Instalar dependencias
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          install.packages("remotes")
          remotes::install_dev("shiny")
          remotes::install_dev("golem")
          remotes::install_local(".")
          tinytex::install_tinytex()
        shell: Rscript {0}
      - name: Execute Script
        run: |
          source('data-raw/relatorios.R')
        shell: Rscript {0}

      - name: Conectando ao ShinyApps
        env:
          SHINY_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINY_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          shiny_token = Sys.getenv("SHINY_TOKEN")
          shiny_secret = Sys.getenv("SHINY_SECRET")
          rsconnect::setAccountInfo('fernandobastos', token = shiny_token, secret = shiny_secret)
        shell: Rscript {0}

      - name: Deploy to ShinyApps
        run: |
          rsconnect::deployApp(appTitle = "subsidios_teste", 
          forceUpdate = getOption("rsconnect.force.update.apps", TRUE))
        shell: Rscript {0}